import type { Metadata } from "next";
import "./globals.css";
import { robotoMono } from "./utils/font";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoMono.variable} ${robotoMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Navbar />
          {children}
        <Footer />
      </body>
    </html>
  );
}
