const STRING_CONSTANTS: Record<string, string> = {
    instagramLink: "https://www.instagram.com/nus_mc/",
    telegramLink: "https://t.me/+x4sQ_J0AlJQ0NWU1",
    linkedinLink: "https://www.linkedin.com/company/myanmar-community-national-university-of-singapore",
    youtubeLink: "https://www.youtube.com/channel/UCU6g_X7SMe0av-3jLy3yK5A",
    facebookLink: "https://www.facebook.com/nusmyanmar",
    events: "Events",
    joinUs: "Join Us",
    contactUs: "Contact Us",
    motto: "Connecting NUS through Myanmar Culture",
    whoWeAre: "Who We Are",
    whoWeAreDescription: "We are a community of current NUS Myanmar students and alumni that aim to provide NUS Myanmar students that organises events and celebrations that bring us closer to our roots.",
    missionTitle: "Mission",
    mission: "To foster cultural exchange and promote mutual support among Myanmar students at NUS and other student communities.",
    visionTitle: "Vision",
    vision: "To build a vibrant and united community of Burmese studensts through shared memorable experiences that inspires connection, growth and long-lasting bonds.",
    bePartOfCommunity: "Be part of this wholesome community!",
    bePartOfCommunityDescription: "Whether as a member, a subcommittee volunteer, or part of our ExCo, we welcome everyone who shares a passion for Myanmar culture and community. Join us in celebrating our heritage, supporting one another, and creating unforgettable experiences together!",
    bePartOfMcnus: "Be part of MCNUS",
    bePartOfMcnusDescription: "It's free!",
    contactTitle: "Get in Touch",
    contactDescription: "we dun bite",
    faqs: "FAQs",
    faqQuestion1: "Do I have to be burmese to join?",
    faqAnswer1: "No",
    faqQuestion2: "Is there a min commitment for the CCA?",
    faqAnswer2: "No, just show up for our events. However, we highly encourage you to attend as many events as possible because they’re FUN!",
    faqQuestion3: "Do I get SEP points?",
    faqAnswer3: "No, MCNUS is not official yet but your participation would greatly help with officialising",
    unansweredQuestions: "Unanswered questions?",
    emailUs: "Email us at mcnus@gmail.com or slide into our dms.",
    admissioEnquiries: "For admissions-related enquiries",
    referToAskAdmissions: "Refer to askadmissions website and follow the steps there accordingly."
}

export default STRING_CONSTANTS;